name: boardgames
channels:
  - defaults
dependencies:
  - python=3.13
  - numpy
  - pip
  - pip:
      - psycopg2-binary
      - pgvector
      - pypdf
      - python-docx
      - python-dotenv
      - fastapi
      - uvicorn[standard]
      - google-genai
      - pytesseract
      - pdf2image
      - python-multipart
      - requests
